### PR TITLE
Wth is a pullrequest

### PR DESCRIPTION
**Pull request by SirCossack**
Added signing and logging users in... poorly.

### CODE REVIEW

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Task Requirements
1. **Choose Authentication Mechanism**: Implement user login and registration functionality using a chosen authentication mechanism (Supabase Auth, Firebase Auth, Clerk, or custom JWT).
2. **Secure Data**: Ensure user data, including passwords, are stored securely. Passwords should be hashed before being saved to the database.
3. **Handle Sessions and Tokens**: If using JWT, handle the generation, storage, and verification of tokens. For other services, follow the provider's documentation.
4. **Prepare User Interface (UI)**: Implement a frontend interface for login and registration. Ensure that only logged-in users can access certain parts of the application.

### Code Changes Review

#### 1. **cloud_storage/__init__.py**
- **Removed code**: The code related to Supabase client initialization was removed.
- **Feedback**: This removal indicates a shift away from Supabase for authentication.

#### 2. **cloud_storage/cloud_storage/__init__.py**
- **Renamed file**: No content changes.
- **Feedback**: No impact on task requirements.

#### 3. **cloud_storage/cloud_storage/__pycache__/**
- **Added compiled Python files**: These are auto-generated and not directly reviewed.

#### 4. **cloud_storage/cloud_storage/asgi.py**
- **Added file**: Standard ASGI configuration for Django.
- **Feedback**: Necessary for Django deployment but not directly related to authentication requirements.

#### 5. **cloud_storage/cloud_storage/settings.py**
- **Added file**: Standard Django settings with the addition of the `login` app.
- **Feedback**:
  - The `login` app is included, which is a good step towards implementing authentication.
  - No specific settings related to JWT or other authentication mechanisms are present.

#### 6. **cloud_storage/cloud_storage/urls.py**
- **Added file**: Includes URL routing for the `login` app.
- **Feedback**: Properly routes URLs to the `login` app, which is necessary for handling login and registration views.

#### 7. **cloud_storage/cloud_storage/wsgi.py**
- **Added file**: Standard WSGI configuration for Django.
- **Feedback**: Necessary for Django deployment but not directly related to authentication requirements.

#### 8. **cloud_storage/db.sqlite3**
- **Added file**: SQLite database file.
- **Feedback**: Contains the database schema and data but not directly reviewed for authentication logic.

#### 9. **cloud_storage/login/__init__.py**
- **Added file**: Initializes Supabase client using credentials from `auth`.
- **Feedback**:
  - Indicates the use of Supabase for authentication, aligning with the first task requirement.
  - However, no implementation details for login or registration are provided.

#### 10. **cloud_storage/login/__pycache__/**
- **Added compiled Python files**: These are auto-generated and not directly reviewed.

#### 11. **cloud_storage/login/admin.py**
- **Renamed file**: No content changes.
- **Feedback**: No impact on task requirements.

#### 12. **cloud_storage/login/apps.py**
- **Renamed file and modified class name**: Changed `CloudStorageConfig` to `LoginConfig`.
- **Feedback**: Properly configures the `login` app but does not directly implement authentication logic.

#### 13. **cloud_storage/login/migrations/__init__.py**
- **Added file**: Standard Django migrations initialization.
- **Feedback**: Necessary for database migrations but not directly related to authentication requirements.

### Summary
The provided code changes partially address the task requirements:
1. The code indicates an initial setup for using Supabase for authentication (`login/__init__.py`), but there is no detailed implementation of user login and registration functionality.
2. There is no evidence of secure data handling (e.g., password hashing) in the provided changes.
3. There is no handling of sessions and tokens (e.g., JWT) in the provided changes.
4. There is no implementation of a frontend interface for login and registration in the provided changes.

### Recommendations
To fully meet the task requirements, consider the following:
1. Implement detailed user login and registration functionality using Supabase or another chosen authentication mechanism.
2. Ensure that user passwords are hashed before being stored in the database.
3. If using JWT, implement token generation, storage, and verification.
4. Develop a frontend interface for user login and registration, ensuring restricted access to certain parts of the application for logged-in users only.

Example implementation for password hashing in Django:
```python
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password

# Creating a new user with hashed password
user = User.objects.create(username='username', password=make_password('password'))
```

Example implementation for JWT in Django:
```python
import jwt
from datetime import datetime, timedelta

# Generate JWT token
def generate_jwt(user):
    payload = {
        'user_id': user.id,
        'exp': datetime.utcnow() + timedelta(days=1),
        'iat': datetime.utcnow()
    }
    token = jwt.encode(payload, 'secret_key', algorithm='HS256')
    return token

# Verify JWT token
def verify_jwt(token):
    try:
        payload = jwt.decode(token, 'secret_key', algorithms=['HS256'])
        return payload['user_id']
    except jwt.ExpiredSignatureError:
        return None
    except jwt.InvalidTokenError:
        return None
```

These steps will ensure that all task requirements are fully met.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Summary
The task requirements were to implement user login and registration functionality, ensuring secure data handling, session management, and a user interface for login and registration. The provided code changes partially meet these requirements. Below is a detailed review based on the task requirements.

### Review of Code Changes

#### 1. **Mechanism of Authentication**
The task allows using third-party services like Supabase Auth, Firebase Auth, Clerk, or implementing a custom solution with JWT. The code uses Supabase Auth for authentication.

- **cloud_storage/__init__.py**: Removed code related to Supabase client initialization.
- **cloud_storage/login/__init__.py**: Re-added Supabase client initialization.

The choice of Supabase Auth is appropriate and meets the requirement.

#### 2. **Secure Data Handling**
The task requires ensuring that user data, especially passwords, are stored securely and hashed before saving to the database.

- **cloud_storage/login/views.py**: The `signing` function directly uses the provided password without hashing it manually. However, Supabase Auth handles password hashing internally, which is acceptable.

```python
def signing(request):
    supabase.auth.sign_up({'email': request.POST['Email'], 'password': request.POST['Password']})
    return HttpResponseRedirect("/loggedin/")
```

This meets the requirement as long as Supabase Auth handles password hashing securely.

#### 3. **Session and Token Management**
The task requires handling sessions and tokens if implementing a custom authentication system. For third-party services, follow their documentation.

- **cloud_storage/login/views.py**: The `login` function handles user login using Supabase's `sign_in_with_password` method. The `loggedin` function checks if the user is authenticated.

```python
def login(request):
    try:
        supabase.auth.sign_in_with_password({'email': request.POST['Email'], 'password': request.POST['Password']})
    except AuthApiError:
        return HttpResponseRedirect('/signup/')
    except AuthInvalidCredentialsError:
        raise AuthInvalidCredentialsError("Please enter valid credentials.")
    return HttpResponseRedirect("/loggedin/")
```

This meets the requirement for session management using Supabase Auth.

#### 4. **User Interface (UI)**
The task requires implementing a frontend interface for login and registration, ensuring that only logged-in users can access certain parts of the application.

- **cloud_storage/login/templates/login.html**: A basic HTML form for login and signup is provided.
- **cloud_storage/login/static/login.css**: Basic CSS for styling the form.

```html
<form action="/{{action}}/" method="post">
    {% csrf_token %}
    <label for="Email">E-mail: </label>
    <input id="Email" type="text" name="Email" value="{{ current_email }}">
    <label for="Password">Password: </label>
    <input id="Password" type="text" name="Password" value="{{ current_password }}">
    <input type="submit" value={{signorlog}}>
</form>
```

This partially meets the requirement. The UI is very basic and lacks proper styling and user experience enhancements. Additionally, there is no clear indication of restricted access for logged-in users only.

### Bugs and Issues
1. **Hardcoded Secret Key**:
   - **cloud_storage/cloud_storage/settings.py**: The secret key is hardcoded, which is insecure.
   ```python
   SECRET_KEY = 'django-insecure-tbf=j58#cegcp+d37xggy0gzu7l+(#1&#vdg97@xauek%^nr+4'
   ```
   Suggestion: Use environment variables to store sensitive information.
   ```python
   import os
   SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'default-secret-key')
   ```

2. **Plaintext Passwords in Forms**:
   - **cloud_storage/login/templates/login.html**: Passwords are not masked in the form.
   ```html
   <input id="Password" type="text" name="Password" value="{{ current_password }}">
   ```
   Suggestion: Change the input type to `password`.
   ```html
   <input id="Password" type="password" name="Password" value="{{ current_password }}">
   ```

3. **Error Handling**:
   - **cloud_storage/login/views.py**: The error handling for invalid credentials raises an exception without user-friendly feedback.
   ```python
   except AuthInvalidCredentialsError:
       raise AuthInvalidCredentialsError("Please enter valid credentials.")
   ```
   Suggestion: Provide user-friendly error messages.
   ```python
   except AuthInvalidCredentialsError:
       return render(request, 'login.html', context={'action': 'login', 'signorlog': "Log in:", 'note': "Invalid credentials"})
   ```

### Conclusion
The provided code changes partially meet the task requirements. The authentication mechanism using Supabase Auth is correctly implemented, but the UI needs improvement for better user experience. Additionally, there are security concerns with hardcoded secret keys and plaintext passwords in forms that need to be addressed. Error handling should also be improved to provide user-friendly feedback.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Summary
The task requirements were to implement user login and registration functionality, ensuring secure data handling, session management, and a user interface for login and registration. The provided code changes partially meet these requirements. Below is a detailed review based on the task requirements.

### Authentication Mechanism
The code uses Supabase Auth for authentication, which is a valid choice as per the task requirements.

### Secure Data Handling
The code does not explicitly show how passwords are hashed before being stored in the database. However, since Supabase Auth is used, it can be assumed that Supabase handles password hashing securely.

### Session and Token Management
The code does not show explicit handling of sessions or tokens. Supabase Auth handles authentication tokens internally, but it would be better to see explicit session management in the Django application.

### User Interface (UI)
The code includes a basic HTML template for login and registration and a CSS file for styling. The UI implementation is minimal but functional.

### Detailed Review

#### `cloud_storage/__init__.py`
- The removed code related to Supabase initialization is now moved to `login/__init__.py`.

#### `cloud_storage/cloud_storage/__init__.py`
- A comment indicating where the authentication and UI are implemented.

#### `cloud_storage/cloud_storage/asgi.py`
- Standard ASGI configuration for Django. No issues here.

#### `cloud_storage/cloud_storage/settings.py`
- Standard Django settings with the addition of the `login` app.
- The secret key is fetched from environment variables, which is good practice.
- The database is set to use SQLite, which is fine for development.

#### `cloud_storage/cloud_storage/urls.py`
- URL patterns include the admin site and the `login` app URLs.

#### `cloud_storage/cloud_storage/wsgi.py`
- Standard WSGI configuration for Django. No issues here.

#### `cloud_storage/db.sqlite3`
- The SQLite database file is included. No issues here.

#### `cloud_storage/login/__init__.py`
- Supabase client initialization moved here. This is fine.

#### `cloud_storage/login/admin.py`, `cloud_storage/login/apps.py`, `cloud_storage/login/migrations/__init__.py`, `cloud_storage/login/models.py`, `cloud_storage/login/tests.py`
- These files are either renamed or unchanged. No issues here.

#### `cloud_storage/login/static/login.css`
- Basic CSS for styling the login and registration forms. Functional but could be improved for better user experience.

#### `cloud_storage/login/templates/login.html`
- Basic HTML template for login and registration.
- The form uses POST method with CSRF protection, which is good.
- The template dynamically changes based on whether it's for login or signup.

#### `cloud_storage/login/urls.py`
- URL patterns for login, signup, and post-login views are defined correctly.

#### `cloud_storage/login/views.py`
- Implements views for login, signup, and post-login.
- Uses Supabase Auth for user authentication.
- Handles invalid credentials and redirects appropriately.
- The `loggedin` view checks if the user is authenticated and displays their email.

### Bugs and Issues
1. **Session Management**: There is no explicit session management in the Django application. It relies entirely on Supabase Auth.
2. **Error Handling**: The error handling could be more robust. For example, catching generic exceptions might lead to unhandled edge cases.
3. **UI/UX**: The user interface is very basic and could be improved for a better user experience.

### Suggestions for Improvement
1. **Session Management**:
   - Implement Django session management to store user sessions.
   ```python
   from django.contrib.auth import login as auth_login, logout as auth_logout

   def login(request):
       try:
           user = supabase.auth.sign_in_with_password({'email': request.POST['Email'], 'password': request.POST['Password']})
           auth_login(request, user)
       except AuthApiError:
           return HttpResponseRedirect('/signup/')
       except AuthInvalidCredentialsError:
           return render(request, 'login.html', context={'action': 'login', 'signorlog': "Log in:", 'note': "Invalid credentials"})
       return HttpResponseRedirect("/loggedin/")
   ```

2. **Error Handling**:
   - Improve error handling by catching specific exceptions and providing user-friendly messages.
   ```python
   def signing(request):
       try:
           supabase.auth.sign_up({'email':request.POST['Email'], 'password': request.POST['Password']})
       except AuthInvalidCredentialsError:
           return render(request, 'login.html', context={'action': 'signing', 'signorlog': "Sign up:", "note": "Invalid credentials"})
       except Exception as e:
           return render(request, 'login.html', context={'action': 'signing', 'signorlog': "Sign up:", "note": str(e)})
       return HttpResponseRedirect("/loggedin/")
   ```

3. **UI/UX**:
   - Enhance the UI with better styling and user feedback.
   ```html
   <style>
       .error {
           color: red;
       }
   </style>
   ```

### Conclusion
The provided code changes partially meet the task requirements. While the basic functionality for user login and registration using Supabase Auth is implemented, there are areas that need improvement, particularly in session management, error handling, and UI/UX enhancements.

**Comment by SirCossack** [comment]
Merging the PR anyway:

- Session management with Django would require creating users in Django models. They are alredy made in Supabase Auth. That's the whole reason for using Supabase Auth.
-  Added some error handling as requested
- I learned enough HTML/CSS today. Leave me alone Nerdy, the errors can be black. I still have a whole new cloud storage frontend to design tommorow and I can't wait to f*** it up.

**Review by NerdbordMentor — APPROVED** [review]
Force approved. Hope you're not cheating!

**Pull request merged**
